module.exports = Object.freeze({
    UNAUTHORIZED_USER: 'User is not authorized.',//'Unauthorized User',
    VALIDATION_ERROR: 'The data is not valid.',//'Validation Error',
    FORBIDDEN_ZONE: 'Forbidden Zone',
    SUCCESS: "Success",
    FAILED: "Failed",
    NO_USER_EXISTS: 'User does not exist.',//"No User Exists",
    SOMETHING_WRONG: "Something wrong happened.",
    USER_ALREADY_EXISTS: "User already exists.",
    NOT_VALID_OTP: 'Please enter a valid OTP.',//"Not a Valid OTP",
    NOT_VALID_FORMAT: "Not a valid format.",
    FILE_NOT_EMPTY: "File can't be empty.",
    PHONE_NUMBER_EXISTS: "User already exists.",
    EMAIL_EXISTS: "Email ID already exists.",
    USER_NOT_VERIFIED: 'User is not verified.',//"User Not Verified",
    INVALID_PASSWORD: 'Mobile number and password does not match',//"Invalid password.",
    VALID_PASSWORD: "VALID PASSWORD",
    NO_USER_DATA: "No user data.",
    NO_DOCUMENT: "No document data.",
    ANONYMOUS_USER: "Anonymous",
    SCHEME_VALID: "Valid",
    SCHEME_DELETED: "Scheme deleted.",
});