export const MailActionTypes = {
  UPDATE_MAILS: "UPDATE_MAILS",
  FETCH_MAILS_START: "FETCH_MAILS_START",
  FETCH_MAILS_SUCCESS: "FETCH_MAILS_SUCCESS",
  FETCH_MAILS_FAILURE: "FETCH_MAILS_FAILURE",
  FETCH_MAIL_DETAIL_START: "FETCH_MAIL_DETAIL_START",
  FETCH_MAIL_DETAIL_SUCCESS: "FETCH_MAIL_DETAIL_SUCCESS",
  FETCH_MAIL_DETAIL_FAILURE: "FETCH_MAIL_DETAIL_FAILURE",
};

export default MailActionTypes;
