export const MailSendActionTypes = {
  MAIL_SEND_START: "MAIL_SEND_START",
  MAIL_SEND_SUCCESS: "MAIL_SEND_SUCCESS",
  MAIL_SEND_FAILURE: "MAIL_SEND_FAILURE",
  MAIL_SEND_FORM: "MAIL_SEND_FORM",
  MAIL_SEND_LOADING: "MAIL_SEND_LOADING",
  UPDATE_MAIL_BODY: "UPDATE_MAIL_BODY",
};

export default MailSendActionTypes;
