export const MailTemplatesActionTypes = {
  UPDATE_MAIL_TEMPLATES: "UPDATE_MAIL_TEMPLATES",
  FETCH_MAIL_TEMPLATES_START: "FETCH_MAIL_TEMPLATES_START",
  FETCH_MAIL_TEMPLATES_SUCCESS: "FETCH_MAIL_TEMPLATES_SUCCESS",
  FETCH_MAIL_TEMPLATES_FAILURE: "FETCH_MAIL_TEMPLATES_FAILURE",
  UPDATE_MAIL_TEMPLATE_BODY: "UPDATE_MAIL_TEMPLATE_BODY",
  UPDATE_MAIL_TEMPLATE_PARAMS: "UPDATE_MAIL_TEMPLATE_PARAMS",
  FETCH_MAIL_TEMPLATE_DETAIL: "FETCH_MAIL_TEMPLATE_DETAIL",
  FETCH_MAIL_TEMPLATE_START: "FETCH_MAIL_TEMPLATE_START",
  FETCH_MAIL_TEMPLATE_SUCCESS: "FETCH_MAIL_TEMPLATE_SUCCESS",
  FETCH_MAIL_TEMPLATE_FAILURE: "FETCH_MAIL_TEMPLATE_FAILURE",
  DELETE_MAIL_TEMPLATE_START: "DELETE_MAIL_TEMPLATE_START",
  DELETE_MAIL_TEMPLATE_SUCCESS: "DELETE_MAIL_TEMPLATE_SUCCESS",
  DELETE_MAIL_TEMPLATE_FAILURE: "DELETE_MAIL_TEMPLATE_FAILURE",
};

export default MailTemplatesActionTypes;
